"use client";
import { useEffect,useState } from "react";
import { CalendarDays,Clock3,Plus,Trash2 } from "lucide-react";
import AppShell from "@/components/AppShell";
export default function SchedulePage(){
 const [lessons,setLessons]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[open,setOpen]=useState(false);
 const load=()=>{fetch("/api/schedule").then(r=>r.json()).then(d=>setLessons(d.lessons||[]));fetch("/api/classes").then(r=>r.json()).then(d=>setClasses(d.classes||[]))};useEffect(load,[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({classroomId:f.get("classroomId"),title:f.get("title"),scheduledAt:f.get("scheduledAt")})});setOpen(false);load()}
 async function del(id:string){await fetch("/api/schedule",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()}
 return <AppShell><div className="cf-page"><div className="cf-page-head"><div><span className="cf-overline">PLANNER</span><h1>Schedule</h1><p>Plan upcoming lessons and live sessions.</p></div><button className="cf-primary small" onClick={()=>setOpen(true)}><Plus size={16}/> Schedule lesson</button></div>{lessons.length?<div className="cf-timeline">{lessons.map(l=><article key={l.id}><div className="cf-date-box"><span>{l.scheduled_at?new Date(l.scheduled_at).toLocaleString("en",{month:"short"}):"TBD"}</span><strong>{l.scheduled_at?new Date(l.scheduled_at).getDate():"—"}</strong></div><div className="grow"><b>{l.title}</b><span>{l.classroom_name} · {l.subject}</span><small><Clock3 size={13}/>{l.scheduled_at?new Date(l.scheduled_at).toLocaleString():"Not scheduled"}</small></div><button className="cf-icon-danger" onClick={()=>del(l.id)}><Trash2 size={16}/></button></article>)}</div>:<div className="cf-empty"><div className="cf-empty-icon"><CalendarDays/></div><h3>Nothing scheduled</h3><p>Add your first lesson to build a clean teaching calendar.</p></div>}{open&&<div className="cf-modal"><form onSubmit={create} className="cf-modal-card"><h2>Schedule lesson</h2><label>Class<select name="classroomId" required>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Lesson title<input name="title" required/></label><label>Date and time<input type="datetime-local" name="scheduledAt" required/></label><div className="cf-submit"><button type="button" className="cf-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="cf-primary">Schedule</button></div></form></div>}</div></AppShell>
}
