"use client";
import { useEffect,useState } from "react";
import { ClipboardList,Plus,Trash2 } from "lucide-react";
import AppShell from "@/components/AppShell";
export default function AssignmentsPage(){
 const [items,setItems]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[open,setOpen]=useState(false);
 const load=()=>{fetch("/api/assignments").then(r=>r.json()).then(d=>setItems(d.assignments||[]));fetch("/api/classes").then(r=>r.json()).then(d=>setClasses(d.classes||[]))};useEffect(load,[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await fetch("/api/assignments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({classroomId:f.get("classroomId"),title:f.get("title"),description:f.get("description"),dueAt:f.get("dueAt")||null})});setOpen(false);load()}
 async function del(id:string){await fetch("/api/assignments",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()}
 return <AppShell><div className="cf-page"><div className="cf-page-head"><div><span className="cf-overline">COURSEWORK</span><h1>Assignments</h1><p>Create and track work for each class.</p></div><button className="cf-primary small" onClick={()=>setOpen(true)}><Plus size={16}/> New assignment</button></div>{items.length?<div className="cf-data-list cards">{items.map(a=><article key={a.id}><div className="cf-round-icon"><ClipboardList size={18}/></div><div className="grow"><b>{a.title}</b><span>{a.classroom_name}{a.due_at?" · Due "+new Date(a.due_at).toLocaleDateString():""}</span><p>{a.description}</p></div><span className="cf-chip">{a.submission_count??0} submissions</span><button className="cf-icon-danger" onClick={()=>del(a.id)}><Trash2 size={16}/></button></article>)}</div>:<div className="cf-empty"><div className="cf-empty-icon"><ClipboardList/></div><h3>No assignments</h3><p>Create one when you’re ready to give students work.</p></div>}{open&&<div className="cf-modal"><form onSubmit={create} className="cf-modal-card"><h2>New assignment</h2><label>Class<select name="classroomId" required>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Description<textarea name="description"/></label><label>Due date<input type="datetime-local" name="dueAt"/></label><div className="cf-submit"><button type="button" className="cf-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="cf-primary">Create</button></div></form></div>}</div></AppShell>
}
