"use client";
import { useEffect,useState } from "react";
import { ExternalLink,FolderOpen,Plus,Trash2 } from "lucide-react";
import AppShell from "@/components/AppShell";
export default function ResourcesPage(){
 const [items,setItems]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[open,setOpen]=useState(false);
 const load=()=>{fetch("/api/resources").then(r=>r.json()).then(d=>setItems(d.resources||[]));fetch("/api/classes").then(r=>r.json()).then(d=>setClasses(d.classes||[]))};useEffect(load,[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await fetch("/api/resources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({classroomId:f.get("classroomId"),title:f.get("title"),url:f.get("url"),resourceType:"link"})});setOpen(false);load()}
 async function del(id:string){await fetch("/api/resources",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()}
 return <AppShell><div className="cf-page"><div className="cf-page-head"><div><span className="cf-overline">MATERIALS</span><h1>Resources</h1><p>Keep lesson links and study material organized by class.</p></div><button className="cf-primary small" onClick={()=>setOpen(true)}><Plus size={16}/> Add resource</button></div>{items.length?<div className="cf-data-list cards">{items.map(r=><article key={r.id}><div className="cf-round-icon"><FolderOpen size={18}/></div><div className="grow"><b>{r.title}</b><span>{r.classroom_name}</span></div><a className="cf-secondary mini" href={r.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Open</a><button className="cf-icon-danger" onClick={()=>del(r.id)}><Trash2 size={16}/></button></article>)}</div>:<div className="cf-empty"><div className="cf-empty-icon"><FolderOpen/></div><h3>No resources</h3><p>Add useful links for your students. File uploads can be connected to object storage later.</p></div>}{open&&<div className="cf-modal"><form onSubmit={create} className="cf-modal-card"><h2>Add resource</h2><label>Class<select name="classroomId" required>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>URL<input type="url" name="url" required placeholder="https://"/></label><div className="cf-submit"><button type="button" className="cf-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="cf-primary">Add</button></div></form></div>}</div></AppShell>
}
