"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft,Check,Users } from "lucide-react";
import AppShell from "@/components/AppShell";
export default function CreateClass(){
 const router=useRouter();const [capacity,setCapacity]=useState(5);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/auth/me").then(r=>r.json()).then(d=>{if(!d.user)return router.push("/login");setCapacity(Math.min(5,Math.max(1,Number(d.user.default_class_size)||5)))});},[router]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/classes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),subject:f.get("subject"),description:f.get("description"),capacity,allowJoinByCode:true})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||"Could not create class");router.push("/dashboard")}
 return <AppShell><div className="cf-page narrow"><button className="cf-back" onClick={()=>router.back()}><ArrowLeft size={16}/> Back</button><div className="cf-page-head"><div><span className="cf-overline">NEW CLASS</span><h1>Create a focused classroom</h1><p>Choose exactly how many students can join this class.</p></div></div><form className="cf-form-card" onSubmit={submit}><div className="cf-form-grid"><label>Class name<input name="name" required placeholder="e.g. Physics 101"/></label><label>Subject<input name="subject" required placeholder="Physics"/></label><label className="full">Description<textarea name="description" placeholder="What will students learn in this class?"/></label></div><div className="cf-field"><b>Maximum live students</b><span>When the class reaches this limit, new students can’t join until you increase it.</span><div className="cf-capacity">{[1,2,3,4,5].map(n=><button type="button" onClick={()=>setCapacity(n)} className={capacity===n?"active":""} key={n}>{capacity===n&&<Check size={14}/>}<strong>{n}</strong><span>{n===1?"student":"students"}</span></button>)}</div></div><div className="cf-info"><Users size={18}/><div><b>Small classes by design</b><span>Start with 1–5 students for a more personal learning experience. The database supports larger capacities later.</span></div></div>{error&&<div className="cf-error">{error}</div>}<div className="cf-submit"><button type="button" className="cf-secondary" onClick={()=>router.back()}>Cancel</button><button className="cf-primary" disabled={busy}>{busy?"Creating...":"Create class"}</button></div></form></div></AppShell>
}
