"use client";
import { useEffect,useState } from "react";
import { CheckCircle2,Settings } from "lucide-react";
import AppShell from "@/components/AppShell";
export default function SettingsPage(){
 const [s,setS]=useState<any>(null),[saved,setSaved]=useState(false);
 useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(d=>setS(d.settings))},[]);
 if(!s)return <AppShell><div className="cf-page"><div className="cf-empty"><div className="cf-empty-icon"><Settings/></div><h3>Loading settings…</h3></div></div></AppShell>;
 async function save(){const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:s.name,defaultClassSize:s.default_class_size,emailNotifications:s.email_notifications,classReminders:s.class_reminders,preferredTheme:s.preferred_theme})});if(r.ok){setSaved(true);setTimeout(()=>setSaved(false),1600)}}
 return <AppShell><div className="cf-page narrow"><div className="cf-page-head"><div><span className="cf-overline">ACCOUNT</span><h1>Settings</h1><p>Control your profile and classroom preferences.</p></div></div><section className="cf-settings-card"><div className="cf-settings-section"><h3>Profile</h3><label>Name<input value={s.name||""} onChange={e=>setS({...s,name:e.target.value})}/></label><label>Email<input value={s.email||""} disabled/></label></div><div className="cf-settings-section"><h3>Teaching preferences</h3><label>Default class size<select value={s.default_class_size} onChange={e=>setS({...s,default_class_size:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} {n===1?"student":"students"}</option>)}</select></label></div><div className="cf-settings-section"><h3>Notifications</h3><label className="cf-toggle-row"><div><b>Email notifications</b><span>Get account and class updates by email.</span></div><input type="checkbox" checked={!!s.email_notifications} onChange={e=>setS({...s,email_notifications:e.target.checked})}/></label><label className="cf-toggle-row"><div><b>Class reminders</b><span>Receive reminders before scheduled lessons.</span></div><input type="checkbox" checked={!!s.class_reminders} onChange={e=>setS({...s,class_reminders:e.target.checked})}/></label></div><div className="cf-submit"><button className="cf-primary" onClick={save}>{saved?<><CheckCircle2 size={16}/> Saved</>:"Save changes"}</button></div></section></div></AppShell>
}
