"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight,GraduationCap,Users } from "lucide-react";
import Brand from "@/components/Brand";
export default function Signup(){
 const router=useRouter();const [role,setRole]=useState<"teacher"|"student">("teacher");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const res=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),email:f.get("email"),password:f.get("password"),role})});const data=await res.json();setBusy(false);if(!res.ok)return setError(data.error||"Could not create account");router.push("/onboarding")}
 return <div className="cf-auth"><div className="cf-auth-panel"><Brand/><div className="cf-auth-card"><span className="cf-overline">START TEACHING BETTER</span><h1>Create your account</h1><p>Set up ClassFlow in less than a minute.</p><div className="cf-role"><button className={role==="teacher"?"active":""} onClick={()=>setRole("teacher")}><GraduationCap size={20}/><b>Teacher</b><span>Create and run classes</span></button><button className={role==="student"?"active":""} onClick={()=>setRole("student")}><Users size={20}/><b>Student</b><span>Join classes and learn</span></button></div><form onSubmit={submit}><label>Name<input name="name" required placeholder="Your full name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" minLength={8} required placeholder="At least 8 characters"/></label>{error&&<div className="cf-error">{error}</div>}<button className="cf-primary" disabled={busy}>{busy?"Creating account...":<>Continue <ArrowRight size={17}/></>}</button></form><div className="cf-auth-foot">Already have an account? <button onClick={()=>router.push("/login")}>Log in</button></div></div></div><div className="cf-auth-visual"><div className="cf-visual-orb"/><div className="cf-preview-card"><span>LIVE CLASS</span><h3>Physics · Motion & Forces</h3><div className="cf-preview-video"><div className="avatar xxl">SJ</div><i>Teacher speaking</i></div><div className="cf-preview-peers">{["AK","SM","FA","+2"].map(x=><div key={x}>{x}</div>)}</div></div></div></div>
}
