"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight,BookOpen,Copy,Plus,Users,Video } from "lucide-react";
import AppShell from "@/components/AppShell";
type C={id:string;name:string;subject:string;class_code:string;capacity:number;student_count:number};
export default function Dashboard(){
 const router=useRouter();const [user,setUser]=useState<any>(null);const [classes,setClasses]=useState<C[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([fetch("/api/auth/me").then(r=>r.json()),fetch("/api/classes").then(r=>r.json())]).then(([u,c])=>{if(!u.user)return router.push("/login");if(!u.user.onboarding_complete)return router.push("/onboarding");setUser(u.user);setClasses(c.classes||[]);setLoading(false)})},[router]);
 return <AppShell><div className="cf-page"><div className="cf-page-head"><div><span className="cf-overline">TEACHER WORKSPACE</span><h1>{loading?"Loading…":"Good to see you, "+(user?.name?.split(" ")[0]||"Teacher")}</h1><p>Everything you need to run your next class, without the clutter.</p></div><button className="cf-primary small" onClick={()=>router.push("/create-class")}><Plus size={16}/> New class</button></div><div className="cf-metrics"><article><span className="cf-metric-icon"><BookOpen/></span><div><strong>{classes.length}</strong><span>Classes</span></div></article><article><span className="cf-metric-icon"><Users/></span><div><strong>{classes.reduce((a,c)=>a+Number(c.student_count||0),0)}</strong><span>Students</span></div></article><article><span className="cf-metric-icon"><Video/></span><div><strong>{classes.filter(c=>Number(c.student_count)>0).length}</strong><span>Ready to go live</span></div></article></div><section className="cf-section"><div className="cf-section-head"><div><span className="cf-overline">YOUR CLASSES</span><h2>Pick up where you left off</h2></div></div>{classes.length===0?<div className="cf-empty"><div className="cf-empty-icon"><BookOpen/></div><h3>Create your first class</h3><p>Choose a class size, share the code, then start a private live room.</p><button className="cf-primary small" onClick={()=>router.push("/create-class")}><Plus size={16}/> Create class</button></div>:<div className="cf-live-grid">{classes.map(c=><article className="cf-live-card" key={c.id}><div className="cf-live-cover"><span>{c.subject.slice(0,1)}</span><i>{c.subject}</i></div><div className="cf-live-body"><h3>{c.name}</h3><div className="cf-class-stats"><span><Users size={14}/>{c.student_count}/{c.capacity}</span><button onClick={()=>navigator.clipboard?.writeText(c.class_code)}><Copy size={13}/>{c.class_code}</button></div><div className="cf-card-actions"><button className="cf-secondary" onClick={()=>router.push("/classes")}>Manage</button><button className="cf-primary small" onClick={()=>router.push("/classroom?id="+c.id)}>Go live <ArrowRight size={15}/></button></div></div></article>)}</div>}</section></div></AppShell>
}
